import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'

import { StellarsightMark } from '../components/Marks'
import { testnetTxs } from '../lib/api'

type Row = {
  txHash: string
  settledAt: string | null
  amount: string | null
  assetCode: string | null
  from: string | null
  to: string | null
  explorerUrl: string
  scheme: string
  provenance: { label: string; source: string }
  listing: { serviceName: string | null; matchedBy: string } | null
}

type Feed = {
  ok: boolean
  feePayer?: string
  fetchedAt?: string
  rows?: Row[]
  stale?: boolean
  staleReason?: string
  reason?: string
}

/**
 * Same base-URL discipline as lib/api.ts and lib/playground/config.ts: same-origin in
 * production (vercel.json routes /explorer/feed to the function), and the facilitator's
 * dev port locally, where the Vite server would otherwise answer the fetch with its own
 * index.html and the page would report a JSON parse error instead of a feed.
 */
const configuredFeed = import.meta.env.VITE_EXPLORER_URL as string | undefined
const FEED_URL =
  typeof configuredFeed === 'string'
    ? configuredFeed.replace(/\/$/, '')
    : import.meta.env.PROD
      ? ''
      : 'http://localhost:4021'
const POLL_MS = 30_000

const short = (s: string | null, head = 4, tail = 4) =>
  !s ? '—' : s.length > head + tail + 1 ? `${s.slice(0, head)}…${s.slice(-tail)}` : s

const when = (iso: string | null) => {
  if (!iso) return '—'
  const d = new Date(iso)
  const mins = Math.round((Date.now() - d.getTime()) / 60_000)
  if (mins < 1) return 'just now'
  if (mins < 60) return `${mins}m ago`
  if (mins < 1440) return `${Math.round(mins / 60)}h ago`
  return d.toISOString().slice(0, 10)
}

/** What each label means, in one line, so the chip is self-explaining. */
const LABEL_TITLE: Record<string, string> = {
  'scripted-load': 'Generated by our own batch script paying our own seller. Breadth of settlement, not demand.',
  conformance: 'An unmodified @x402/fetch client completing the loop end to end.',
  'nightly-ci': 'The nightly workflow, against this deployment, with a buyer created inside the run.',
  demo: 'The narrated discover → pay → unlock demo loop.',
  setup: 'Account creation, trustlines, or the SAC deploy — not a payment.',
  unlabeled: 'No provenance recorded for this hash. Unlabeled — which is not the same as organic.',
}

export default function Explorer() {
  const [feed, setFeed] = useState<Feed | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let alive = true
    /**
     * `skipWhenHidden` guards the POLL, never the first load. A tab restored in the
     * background is hidden at mount, and skipping that load left the page permanently
     * empty with no error to explain it — the failure mode looked identical to "the feed
     * has nothing in it".
     */
    const load = async (skipWhenHidden = false) => {
      if (skipWhenHidden && document.hidden) return
      try {
        const r = await fetch(`${FEED_URL}/explorer/feed?limit=25`, { headers: { accept: 'application/json' } })
        const j = (await r.json()) as Feed
        if (!alive) return
        if (!j.ok) {
          setError(j.reason ?? `the feed answered ${r.status}`)
          setFeed(null)
        } else {
          setFeed(j)
          setError(null)
        }
      } catch (e) {
        if (alive) setError(e instanceof Error ? e.message : String(e))
      }
    }
    load()
    const timer = setInterval(() => load(true), POLL_MS)
    return () => {
      alive = false
      clearInterval(timer)
    }
  }, [])

  const rows = feed?.rows ?? []
  const live = Boolean(feed?.ok && rows.length)

  return (
    <div className="theme">
      <a className="skip" href="#main">
        Skip to content
      </a>
      <span className="grain" aria-hidden="true" />

      <header className="topbar topbar--solid">
        <div className="shell topbar__in">
          <Link className="topbar__mark" to="/" aria-label="STELLARSIGHT home">
            <StellarsightMark />
            <span>STELLARSIGHT</span>
          </Link>
          <nav className="topbar__nav" aria-label="Sections">
            <Link to="/">Home</Link>
            <Link to="/console">Console</Link>
            <Link to="/playground">Playground</Link>
          </nav>
          <span className={`source-pill source-pill--${live ? 'live' : 'seed'}`}>
            <span className={live ? 'dot dot--pulse' : 'dot'} />
            {live ? 'live feed' : 'baked'}
          </span>
        </div>
      </header>

      <main id="main" className="shell xp">
        <span className="label">Explorer</span>
        <h1 className="console__title">
          Every settlement <em>this facilitator</em> made.
        </h1>
        <p className="xp-lede">
          Read from Horizon at request time, keyed on the fee-payer account that sponsors every one of our settlements.
          Each row carries the reason the payment exists, because a settlement count without that is not evidence of
          anything.
        </p>

        <p className="xp-scope">
          <strong>Scope:</strong> this is the activity of <em>this deployment</em>
          {feed?.feePayer && (
            <>
              {' '}
              (fee-payer{' '}
              <a href={`https://stellar.expert/explorer/testnet/account/${feed.feePayer}`} target="_blank" rel="noreferrer">
                <code>{short(feed.feePayer, 6, 6)}</code>
              </a>
              )
            </>
          )}
          , not an index of every x402 operator on Stellar. Rows labeled <span className="xp-chip xp-chip--scripted-load">scripted load</span> were
          generated by our own scripts — none of the traffic here is third-party demand, and we do not present it as
          such.
        </p>

        {feed?.stale && (
          <p className="xp-banner">
            Showing the last good read — Horizon is not answering right now ({feed.staleReason}).
          </p>
        )}

        {!feed && !error && (
          <p className="xp-banner" role="status">
            Reading this deployment's settlements from Horizon…
          </p>
        )}

        {feed?.ok && !rows.length && (
          <p className="xp-banner">No settlements from this fee-payer yet.</p>
        )}

        {error && !rows.length && (
          <>
            <p className="xp-banner">
              Live feed unavailable ({error}). Showing the transactions baked into this build instead.
            </p>
            <div className="xp-tablewrap">
              <table className="xp-table">
                <thead>
                  <tr>
                    <th>When</th>
                    <th>Step</th>
                    <th>Transaction</th>
                  </tr>
                </thead>
                <tbody>
                  {testnetTxs.slice(0, 25).map((t) => (
                    <tr key={t.hash}>
                      <td>{when(t.settledAt ?? null)}</td>
                      <td>{t.label}</td>
                      <td>
                        <a
                          className="xp-hash"
                          href={`https://stellar.expert/explorer/testnet/tx/${t.hash}`}
                          target="_blank"
                          rel="noreferrer"
                        >
                          <code>{short(t.hash, 8, 6)}</code>
                        </a>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}

        {rows.length > 0 && (
          <div className="xp-tablewrap">
            <table className="xp-table">
              <thead>
                <tr>
                  <th>When</th>
                  <th>Scheme</th>
                  <th>Amount</th>
                  <th>Payer</th>
                  <th>Transaction</th>
                  <th>Listing</th>
                  <th>Why it exists</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.txHash}>
                    <td title={r.settledAt ?? undefined}>{when(r.settledAt)}</td>
                    <td>
                      <code>{r.scheme}</code>
                    </td>
                    <td>
                      {r.amount ? (
                        <>
                          {r.amount} {r.assetCode ?? ''}
                        </>
                      ) : (
                        <span title="This transaction's operations did not resolve to exactly one transfer, so we do not state an amount.">
                          —
                        </span>
                      )}
                    </td>
                    <td>
                      <code>{short(r.from)}</code>
                    </td>
                    <td>
                      <a className="xp-hash" href={r.explorerUrl} target="_blank" rel="noreferrer">
                        <code>{short(r.txHash, 8, 6)}</code>
                      </a>
                    </td>
                    <td>
                      {r.listing ? (
                        <span title={`Matched by ${r.listing.matchedBy} — payee and amount agree with this listing.`}>
                          {r.listing.serviceName ?? '—'}
                          <sup> {r.listing.matchedBy}</sup>
                        </span>
                      ) : (
                        '—'
                      )}
                    </td>
                    <td>
                      <span
                        className={`xp-chip xp-chip--${r.provenance.label}`}
                        title={LABEL_TITLE[r.provenance.label] ?? r.provenance.label}
                      >
                        {r.provenance.label.replace('-', ' ')}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <p className="pg-foot">
          {feed?.fetchedAt && <>Read {when(feed.fetchedAt)}, refreshing every 30 seconds. </>}
          The label map is <code>docs/status/provenance.json</code>; the full list with explorer links is{' '}
          <a href="https://docs.stellarsight.xyz/evidence/testnet-transactions">in the docs</a>. Want to add a row?{' '}
          <Link to="/playground">Make a payment yourself</Link>.
        </p>
      </main>
    </div>
  )
}
